

CREATE USER "MailEnhancementUser"  WITH
  PASSWORD 'MailEnhancementUser'
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  REPLICATION
  CONNECTION LIMIT -1
  VALID UNTIL '2035-12-29 23:10:38+02'
