FROM node:alpine

MAINTAINER Roche Olivier <roolivier@mmiholdings.co.za>

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

COPY dockerfiles/local/env.js /usr/src/app/config/

EXPOSE 4010

CMD [ "npm", "start" ]